### ISSUE TITLE
parse_gtfs crashes when generating road segments

### ISSUE THREAD

**Issue by nickolasclarke** [nickolasclarke/dispatch#14]
output when attempting to parse the latest minneapolis gtfs feed. 
```
Traceback (most recent call last):
  File "parse_gtfs.py", line 234, in <module>
    road_segs, seg_props = GenerateRoadSegments(ptg.load_geo_feed(feed_file))
  File "parse_gtfs.py", line 202, in GenerateRoadSegments
    shape_props['distance'] = [[SegLength(*x) for x in x] for x in shape_props['seg_hash']]
  File "parse_gtfs.py", line 202, in <listcomp>
    shape_props['distance'] = [[SegLength(*x) for x in x] for x in shape_props['seg_hash']]
  File "parse_gtfs.py", line 202, in <listcomp>
    shape_props['distance'] = [[SegLength(*x) for x in x] for x in shape_props['seg_hash']]
  File "parse_gtfs.py", line 184, in SegLength
    xd = p1[0]-p2[0]
TypeError: 'float' object is not subscriptable
```

**Comment by r-barnes** [comment]
`x` should be a 4-tuple of floats which gets unpacked to form the arguments of SegLength. It looks as though it's not getting passed in that way for some reason.
