### ISSUE TITLE
harden parse_gtfs

### ISSUE THREAD

**Issue by nickolasclarke** [nickolasclarke/dispatch#31]
plenty of feeds that otherwise should be supported are not parsed. This is a placeholder to resolve all of these issues.

**Comment by nickolasclarke** [comment]
[validation_results.zip](https://github.com/nickolasclarke/dispatch/files/4235111/validation_results.zip)

**Comment by nickolasclarke** [comment]
currently the most common error seems to be: 

```
b'Service id chosen = frozenset({\'1\'})\nTraceback (most recent call last):\n  File "parse_gtfs.py", line 319, in <module>\n    trips      = GenerateTrips(ptg.load_geo_feed(feed_file), date, service_ids)\n  File "parse_gtfs.py", line 217, in GenerateTrips\n    trips = MatchColumn(trips,\'block_id\')\n  File "parse_gtfs.py", line 138, in MatchColumn\n    assert (df[\'start_\'+colname]==df[\'end_\'+colname]).all()\nAssertionError\n'
```

**Comment by r-barnes** [comment]
Fixed.
